# Generated by Django 6.0.7 on 2026-07-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
